/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pannals;

import Forms.CompatabilityView;
import MasterData.Class.BloodRequestData;
import Other.SearchPopUp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chamod
 */
public class BloodRequest extends javax.swing.JPanel {

    BloodRequestData request = new BloodRequestData();

    /**
     * Creates new form Blood_Request
     */
    public BloodRequest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        txtABO = new javax.swing.JTextField();
        txtTypeId = new javax.swing.JTextField();
        txtRh = new javax.swing.JTextField();
        cmdBlood = new javax.swing.JButton();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtVol = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        txtHospitalId = new javax.swing.JTextField();
        cndNew = new javax.swing.JButton();
        txtConsultant = new javax.swing.JTextField();
        cmdNew = new javax.swing.JButton();
        cmdhospital = new javax.swing.JButton();
        txtDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel67 = new javax.swing.JLabel();

        jPanel11.setBackground(new java.awt.Color(255, 204, 153));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBackground(new java.awt.Color(255, 204, 204));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPanel28.setBackground(new java.awt.Color(255, 102, 102));
        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Blood Group", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel81.setText("ABO");
        jPanel28.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 56, 20));

        jLabel88.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel88.setText("Rh D");
        jPanel28.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 56, 20));

        jLabel89.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel89.setText("Blood Type Id ");
        jPanel28.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, 90, 20));

        txtABO.setEditable(false);
        txtABO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtABOActionPerformed(evt);
            }
        });
        jPanel28.add(txtABO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 122, -1));

        txtTypeId.setEditable(false);
        txtTypeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeIdActionPerformed(evt);
            }
        });
        jPanel28.add(txtTypeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 90, -1));

        txtRh.setEditable(false);
        txtRh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRhActionPerformed(evt);
            }
        });
        jPanel28.add(txtRh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 122, -1));

        cmdBlood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_1.png"))); // NOI18N
        cmdBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBloodActionPerformed(evt);
            }
        });
        jPanel28.add(cmdBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 30, 20));

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel76.setText("Hospital ID");

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel77.setText("Consulltant's ");

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel78.setText("Name");

        txtHospitalName.setEditable(false);

        txtVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolActionPerformed(evt);
            }
        });

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel83.setText("Date");

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel84.setText("Description");

        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel86.setText("Vol");

        txtHospitalId.setEditable(false);
        txtHospitalId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalIdActionPerformed(evt);
            }
        });

        cndNew.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cndNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/24x24/new.png"))); // NOI18N
        cndNew.setText("NEW");
        cndNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cndNewActionPerformed(evt);
            }
        });

        cmdNew.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cmdNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/24x24/save.png"))); // NOI18N
        cmdNew.setText("Save");
        cmdNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNewActionPerformed(evt);
            }
        });

        cmdhospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_1.png"))); // NOI18N
        cmdhospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhospitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtHospitalId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cmdhospital, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel78)
                            .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtConsultant, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVol, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdNew, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cndNew, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel76)
                    .addComponent(txtHospitalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdhospital, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel78))
                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtConsultant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel84)))
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel86))
                            .addComponent(txtVol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel83))
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdNew)
                    .addComponent(cndNew))
                .addContainerGap())
        );

        jPanel11.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 510, 310));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel67.setText("Request For Blood");
        jPanel11.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 161, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cndNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cndNewActionPerformed
        NewForm();
    }//GEN-LAST:event_cndNewActionPerformed

    private void txtHospitalIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalIdActionPerformed

    private void txtVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolActionPerformed

    private void txtABOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtABOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtABOActionPerformed

    private void txtTypeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeIdActionPerformed

    private void txtRhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRhActionPerformed

    private void cmdNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNewActionPerformed
        String HospitalId = txtHospitalId.getText();
        String description = txtDescription.getText();
        String consulten = txtConsultant.getText();
               
        String InsertDate = new SimpleDateFormat("yyyy-mm-dd").format(txtDate.getDate());
        String vol = txtVol.getText();
        //String InsertDate = txtDate.getText();
        String typeid = txtTypeId.getText();
        int a = request.saveRequest(HospitalId, description, consulten, vol, InsertDate, typeid, "0");
        if(a>0){
        JOptionPane.showMessageDialog(null, " Request Enterd Succesfull ");
        NewForm();
        }else{
         JOptionPane.showMessageDialog(null, " Save not complete ");
        }
    }//GEN-LAST:event_cmdNewActionPerformed

    private void cmdhospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhospitalActionPerformed
        System.out.println(" page came  >>>>>");
        SearchPopUp MAS = new SearchPopUp(null, true, 1, "0") {
            @Override
            public void getSelectedValue(String Para1, String para2, String para3, String para4, String para5) {
                txtHospitalId.setText(Para1);
                txtHospitalName.setText(para2);
               // txtReferenceNo.setText(para3);
                //  txtpaymode.setSelectedIndex(Integer.parseInt(para4));
                               
            }
        };
        MAS.setVisible(true);
        MAS = null;
    }//GEN-LAST:event_cmdhospitalActionPerformed

    private void cmdBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBloodActionPerformed
        System.out.println(" page came  >>>>>");
        SearchPopUp MAS = new SearchPopUp(null, true, 2, "0") {
            @Override
            public void getSelectedValue(String Para1, String para2, String para3, String para4, String para5) {
                txtTypeId.setText(Para1);
                txtABO.setText(para2);
               txtRh.setText(para3);
                //  txtpaymode.setSelectedIndex(Integer.parseInt(para4));
                               
            }
        };
        MAS.setVisible(true);
        MAS = null;
    }//GEN-LAST:event_cmdBloodActionPerformed

    public void NewForm(){
    txtHospitalId.setText("");
    txtHospitalName.setText("");
    txtConsultant.setText("");
    txtDescription.setText("");
    txtVol.setText("");
     
     try {
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = new Date();
            String daten = (dateFormat.format(date));
            txtDate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(daten));
        } catch (ParseException ex) {
            Logger.getLogger(BloodRequest.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    txtTypeId.setText("");
    txtRh.setText("");
    txtABO.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBlood;
    private javax.swing.JButton cmdNew;
    private javax.swing.JButton cmdhospital;
    private javax.swing.JButton cndNew;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JTextField txtABO;
    private javax.swing.JTextField txtConsultant;
    private org.jdesktop.swingx.JXDatePicker txtDate;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtHospitalId;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtRh;
    private javax.swing.JTextField txtTypeId;
    private javax.swing.JTextField txtVol;
    // End of variables declaration//GEN-END:variables
}
