/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pannals;

import MasterData.Class.BloodRequestData;
import MasterData.Class.BloodTypeData;
import MasterData.Class.ReportShow;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author chamod
 */
public class RequestView extends javax.swing.JPanel {

    BloodRequestData request = new BloodRequestData();
      BloodTypeData btype = new BloodTypeData();
      ReportShow report = new ReportShow();
      

    /**
     * Creates new form RequestView
     */
    public RequestView() {
        initComponents();
        ShowGrid();
       
    }

    private void ShowGrid() {
        String data[][] = null;
        String colu[] = new String[]{"Hospital Id", "Type", "Description", "<html>Requested<br> Vol</html>", "<html><center>Consulton's <br>Name</center></html>"};
        DefaultTableModel model = new DefaultTableModel(data, colu) {
            //@Override
            public boolean isCellEditable(int x, int y) {
                if (y == 1 || y == 3 || y == 4) {
                    return true;
                } else {
                    return false;
                }
            }
        };

        RequestViewTable.setModel(model);
        RequestViewTable.getTableHeader().setPreferredSize(new Dimension(RequestViewTable.getTableHeader().getPreferredSize().width, 35));
        JTableHeader head = RequestViewTable.getTableHeader();
        head.setFont(head.getFont().deriveFont(Font.BOLD));

        /* DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        RequestViewTable.getColumnModel().getColumn(4).setCellRenderer(rightRenderer); */

        TableColumn colou10 = RequestViewTable.getColumnModel().getColumn(0);
        colou10.setMinWidth(70);
        colou10.setPreferredWidth(70);
        colou10.setMaxWidth(70);

       TableColumn colou11 = RequestViewTable.getColumnModel().getColumn(1);
        colou11.setMinWidth(50);
        colou11.setPreferredWidth(50);
        colou11.setMaxWidth(50);

       
        TableColumn colou12 = RequestViewTable.getColumnModel().getColumn(3);
        colou12.setMinWidth(68);
        colou12.setPreferredWidth(68);
        colou12.setMaxWidth(68);
 
         showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        txtReqNo = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        RequestViewTable = new javax.swing.JTable();
        jLabel79 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();

        jPanel23.setBackground(new java.awt.Color(255, 204, 153));

        jPanel24.setBackground(new java.awt.Color(255, 204, 204));
        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Blood Using No", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel66.setText("Request No ");
        jPanel24.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 22, 90, 20));

        txtReqNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReqNoActionPerformed(evt);
            }
        });
        txtReqNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReqNoKeyReleased(evt);
            }
        });
        jPanel24.add(txtReqNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 102, -1));

        RequestViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(RequestViewTable);

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel79.setText("Blood request details");

        jButton29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/24x24/refresh.png"))); // NOI18N
        jButton29.setText("Refesh");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/24x24/printer.png"))); // NOI18N
        jButton30.setText("Print");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(jButton29))
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel79))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton30)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void showTableData() {
        ResultSet rs;
        DefaultTableModel dtf = new DefaultTableModel();
        DefaultTableModel dt = (DefaultTableModel) RequestViewTable.getModel();
        dt.setRowCount(0);
        try {
            rs = request.ShowRequest(txtReqNo.getText().trim());
            rs.last();

            int count = rs.getRow();
            rs.beforeFirst();
            String data[][] = null;
            data = new String[count][5];
            int x = 0;
            while (rs.next()) {
                Vector v = new Vector();
                dtf = (javax.swing.table.DefaultTableModel) RequestViewTable.getModel();
                
                v.add(data[x][0] = rs.getString("HId"));
                
                ResultSet rs1 = btype.SearchBloodType(rs.getString("TypeId"));
                rs1.beforeFirst();
                rs1.next();
                v.add(data[x][1] = rs1.getString("Type")+rs1.getString("RH"));     
                v.add(data[x][2] = rs.getString("Description"));
                v.add(data[x][3] = rs.getString("RequestVol"));
                v.add(data[x][4] = rs.getString("ConsultentName"));
                dtf.addRow(v);
                
                // confirm = rs.getInt("confirm");
                x = x + 1;
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(RequestView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void txtReqNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReqNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReqNoActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
       txtReqNo.setText("");
        showTableData();
    }//GEN-LAST:event_jButton29ActionPerformed

    private void txtReqNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReqNoKeyReleased
       ShowGrid();
    }//GEN-LAST:event_txtReqNoKeyReleased

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        report.shoePendingRequest();
    }//GEN-LAST:event_jButton30ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RequestViewTable;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField txtReqNo;
    // End of variables declaration//GEN-END:variables
}
