/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Report.Forms;

import DBClass.DBFacade;
import MasterData.Class.ReportShow;
import Other.SearchPopUp;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author chamod
 */
public class Request extends javax.swing.JInternalFrame {
     ReportShow report = new ReportShow();

    /**
     * Creates new form Request
     */
    public Request() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        chkViewPending = new javax.swing.JRadioButton();
        chkViewAllReq = new javax.swing.JRadioButton();
        chkDateOrder = new javax.swing.JRadioButton();
        chkIdOrder = new javax.swing.JRadioButton();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        txtReqIdFrom = new javax.swing.JTextField();
        cmdhospital = new javax.swing.JButton();
        txtReqId5 = new javax.swing.JTextField();
        cmdhospital1 = new javax.swing.JButton();
        cmdPrint = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("BB : Reports - Request ");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/be86d361-1ddd-43e3-8574-e04adf9904b7.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        chkViewPending.setBackground(new java.awt.Color(255, 204, 153));
        buttonGroup1.add(chkViewPending);
        chkViewPending.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkViewPending.setText("View Pending Request");

        chkViewAllReq.setBackground(new java.awt.Color(255, 204, 153));
        buttonGroup1.add(chkViewAllReq);
        chkViewAllReq.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkViewAllReq.setText("View All Request ( With seteled request )");

        chkDateOrder.setBackground(new java.awt.Color(255, 204, 153));
        buttonGroup2.add(chkDateOrder);
        chkDateOrder.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkDateOrder.setText("Date Order");

        chkIdOrder.setBackground(new java.awt.Color(255, 204, 153));
        buttonGroup2.add(chkIdOrder);
        chkIdOrder.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkIdOrder.setText("Request Id Order");

        txtReqIdFrom.setEditable(false);
        txtReqIdFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReqIdFromActionPerformed(evt);
            }
        });

        cmdhospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_1.png"))); // NOI18N
        cmdhospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhospitalActionPerformed(evt);
            }
        });

        txtReqId5.setEditable(false);
        txtReqId5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReqId5ActionPerformed(evt);
            }
        });

        cmdhospital1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_1.png"))); // NOI18N
        cmdhospital1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhospital1ActionPerformed(evt);
            }
        });

        cmdPrint.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cmdPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/24x24/printer.png"))); // NOI18N
        cmdPrint.setText("Print");
        cmdPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrintActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/24x24/delete.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/24x24/new.png"))); // NOI18N
        jButton3.setText("New");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/WhatsApp Image 2017-10-21 at 8.37.13 AM.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkViewAllReq)
                            .addComponent(chkViewPending)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkIdOrder)
                            .addComponent(chkDateOrder)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtReqIdFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(cmdhospital, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtReqId5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(cmdhospital1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(cmdPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jXDatePicker1, jXDatePicker2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkViewPending)
                .addGap(10, 10, 10)
                .addComponent(chkViewAllReq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkDateOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkIdOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtReqIdFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdhospital, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtReqId5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdhospital1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdPrint)
                    .addComponent(jButton3)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReqIdFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReqIdFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReqIdFromActionPerformed

    private void cmdhospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhospitalActionPerformed
        System.out.println(" page came  >>>>>");
        SearchPopUp MAS = new SearchPopUp(null, true, 3, "0") {
            @Override
            public void getSelectedValue(String Para1, String para2, String para3, String para4, String para5) {               
                    txtReqIdFrom.setText(Para1);
            }
        };
        MAS.setVisible(true);
        MAS = null;
    }//GEN-LAST:event_cmdhospitalActionPerformed

    private void txtReqId5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReqId5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReqId5ActionPerformed

    private void cmdhospital1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhospital1ActionPerformed
         System.out.println(" page came  >>>>>");
        SearchPopUp MAS = new SearchPopUp(null, true, 3, "0") {
            @Override
            public void getSelectedValue(String Para1, String para2, String para3, String para4, String para5) {               
                    txtReqId5.setText(Para1);
            }
        };
        MAS.setVisible(true);
        MAS = null;
    }//GEN-LAST:event_cmdhospital1ActionPerformed

    private void cmdPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrintActionPerformed
        if (chkViewPending.isSelected()) { //show only pending request
           report.shoePendingRequest();
        } else if (chkViewAllReq.isSelected()) { // show all request
            if (chkDateOrder.isSelected()) {
                report.showPendingRequestDateOrder(new SimpleDateFormat("yyyy-MM-dd").format(jXDatePicker1.getDate()),new SimpleDateFormat("yyyy-MM-dd").format(jXDatePicker2.getDate()));
            } else if (chkIdOrder.isSelected()) {
               report.shoePendingRequestIDOrder( txtReqId5.getText(), txtReqIdFrom.getText());
            }
        }

    }//GEN-LAST:event_cmdPrintActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton chkDateOrder;
    private javax.swing.JRadioButton chkIdOrder;
    private javax.swing.JRadioButton chkViewAllReq;
    private javax.swing.JRadioButton chkViewPending;
    private javax.swing.JButton cmdPrint;
    private javax.swing.JButton cmdhospital;
    private javax.swing.JButton cmdhospital1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JTextField txtReqId5;
    private javax.swing.JTextField txtReqIdFrom;
    // End of variables declaration//GEN-END:variables
}
