/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import MasterData.Class.BloodRequestData;
import MasterData.Class.BloodTypeData;
import MasterData.Class.GetSetValue;
import MasterData.Class.HospitalData;
import MasterData.Class.ReservedData;
import MasterData.Class.StockData;
import Other.SearchPopUp;
import Pannals.RequestView;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author chamod
 */
public class CompatabilityView extends javax.swing.JInternalFrame {

    HospitalData hdata = new HospitalData();
    BloodTypeData btype = new BloodTypeData();
    GetSetValue setval = new GetSetValue();
    StockData stockdata = new StockData();
    String BType = "";
    ReservedData redata = new ReservedData();
    BloodRequestData bloodrequestdata = new BloodRequestData();

    /**
     * Creates new form CompatabilityView
     */
    public CompatabilityView() {
        initComponents();
        ShowGrid();
        showTableData();
    }

    private void ShowGrid() {
        String data[][] = null;
        String colu[] = new String[]{"Stock Id", "Added Date", "Vol", "Expire Date", "Rh", "ABO"};
        DefaultTableModel model = new DefaultTableModel(data, colu) {
            //@Override
            public boolean isCellEditable(int x, int y) {
                /*  if (y == 1 || y == 3 || y == 4) {
                    return true;
                } else {
                    return false;
                }*/
                return false;
            }
        };

        TblStock.setModel(model);
        TblStock.getTableHeader().setPreferredSize(new Dimension(TblStock.getTableHeader().getPreferredSize().width, 35));
        JTableHeader head = TblStock.getTableHeader();
        head.setFont(head.getFont().deriveFont(Font.BOLD));

        /* DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        RequestViewTable.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);

        TableColumn colou10 = RequestViewTable.getColumnModel().getColumn(0);
        colou10.setMinWidth(80);
        colou10.setPreferredWidth(80);
        colou10.setMaxWidth(80);

        TableColumn colou11 = RequestViewTable.getColumnModel().getColumn(1);
        colou11.setMinWidth(80);
        colou11.setPreferredWidth(80);
        colou11.setMaxWidth(80);
         */
    }

    private void showTableData() {
        ResultSet rs;
        DefaultTableModel dtf = (DefaultTableModel) TblStock.getModel();
        dtf.setRowCount(0);
        try {
            rs = stockdata.GetStock(BType);
            rs.last();

            int count = rs.getRow();
            rs.beforeFirst();
            String data[][] = null;
            data = new String[count][6];
            int x = 0;
            while (rs.next()) {
                Vector v = new Vector();
                dtf = (javax.swing.table.DefaultTableModel) TblStock.getModel();
                v.add(data[x][0] = rs.getString("StockId"));
                v.add(data[x][1] = rs.getString("AddedDate"));
                v.add(data[x][2] = rs.getString("Vol"));
                v.add(data[x][3] = rs.getString("expierDate"));

                ResultSet rs1 = null;
                rs1 = btype.SearchBloodType(rs.getString("TypeId"));
                rs1.beforeFirst();
                rs1.next();

                v.add(data[x][4] = rs1.getString("RH"));
                v.add(data[x][5] = rs1.getString("Type"));

                dtf.addRow(v);
                // confirm = rs.getInt("confirm");
                x = x + 1;
            }
        } catch (Exception ex) {
            Logger.getLogger(RequestView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cmdhospital = new javax.swing.JButton();
        txtHospitalName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtReqId = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        txtConsulltent = new javax.swing.JTextField();
        txtVol = new javax.swing.JTextField();
        txtHospital = new javax.swing.JTextField();
        txtRh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        txtABO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIDblood = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cmdhospital1 = new javax.swing.JButton();
        txtVol4 = new javax.swing.JTextField();
        cmdhospital2 = new javax.swing.JButton();
        txtStockID2 = new javax.swing.JTextField();
        cmdhospital3 = new javax.swing.JButton();
        txtStockID3 = new javax.swing.JTextField();
        txtStockID4 = new javax.swing.JTextField();
        cmdhospital4 = new javax.swing.JButton();
        txtStockID1 = new javax.swing.JTextField();
        txtVol1 = new javax.swing.JTextField();
        txtVol2 = new javax.swing.JTextField();
        txtVol3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TblStock = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BB : Compatability");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/be86d361-1ddd-43e3-8574-e04adf9904b7.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        cmdhospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_1.png"))); // NOI18N
        cmdhospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhospitalActionPerformed(evt);
            }
        });

        txtHospitalName.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Request ID");

        txtReqId.setEditable(false);
        txtReqId.setAutoscrolls(false);
        txtReqId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReqIdActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Request Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel76.setText("Hospital Name");
        jPanel3.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, -1));

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel77.setText("Consulltant's ");
        jPanel3.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 26));

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel78.setText("Name");
        jPanel3.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel88.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel88.setText("Rh D");
        jPanel3.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 40, 20));

        txtConsulltent.setEditable(false);
        txtConsulltent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsulltentActionPerformed(evt);
            }
        });
        jPanel3.add(txtConsulltent, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 160, -1));

        txtVol.setEditable(false);
        txtVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolActionPerformed(evt);
            }
        });
        jPanel3.add(txtVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 160, -1));

        txtHospital.setEditable(false);
        txtHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalActionPerformed(evt);
            }
        });
        jPanel3.add(txtHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 160, -1));

        txtRh.setEditable(false);
        txtRh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRhActionPerformed(evt);
            }
        });
        jPanel3.add(txtRh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 50, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Requested Vol");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel81.setText("ABO");
        jPanel3.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 30, 20));

        txtABO.setEditable(false);
        txtABO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtABOActionPerformed(evt);
            }
        });
        jPanel3.add(txtABO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 60, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("ID");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        txtIDblood.setEditable(false);
        txtIDblood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDbloodActionPerformed(evt);
            }
        });
        jPanel3.add(txtIDblood, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 50, 20));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stock Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdhospital1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_1.png"))); // NOI18N
        cmdhospital1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhospital1ActionPerformed(evt);
            }
        });
        jPanel4.add(cmdhospital1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 30, 20));

        txtVol4.setText("0");
        txtVol4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVol4ActionPerformed(evt);
            }
        });
        jPanel4.add(txtVol4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 70, -1));

        cmdhospital2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_1.png"))); // NOI18N
        cmdhospital2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhospital2ActionPerformed(evt);
            }
        });
        jPanel4.add(cmdhospital2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 30, 20));

        txtStockID2.setEditable(false);
        txtStockID2.setText("0");
        txtStockID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockID2ActionPerformed(evt);
            }
        });
        jPanel4.add(txtStockID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 70, -1));

        cmdhospital3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_1.png"))); // NOI18N
        cmdhospital3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhospital3ActionPerformed(evt);
            }
        });
        jPanel4.add(cmdhospital3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 30, 20));

        txtStockID3.setEditable(false);
        txtStockID3.setText("0");
        txtStockID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockID3ActionPerformed(evt);
            }
        });
        jPanel4.add(txtStockID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 70, -1));

        txtStockID4.setEditable(false);
        txtStockID4.setText("0");
        txtStockID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockID4ActionPerformed(evt);
            }
        });
        jPanel4.add(txtStockID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, -1));

        cmdhospital4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_1.png"))); // NOI18N
        cmdhospital4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhospital4ActionPerformed(evt);
            }
        });
        jPanel4.add(cmdhospital4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 30, 20));

        txtStockID1.setEditable(false);
        txtStockID1.setText("0");
        txtStockID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockID1ActionPerformed(evt);
            }
        });
        jPanel4.add(txtStockID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 70, 20));

        txtVol1.setText("0");
        txtVol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVol1ActionPerformed(evt);
            }
        });
        jPanel4.add(txtVol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 70, -1));

        txtVol2.setText("0");
        txtVol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVol2ActionPerformed(evt);
            }
        });
        jPanel4.add(txtVol2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 70, -1));

        txtVol3.setText("0");
        txtVol3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVol3ActionPerformed(evt);
            }
        });
        jPanel4.add(txtVol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("VOL");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Stock No 1");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Stock No 2");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Stock No 3");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Stock No 4");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stock Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        TblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(TblStock);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/24x24/rss.png"))); // NOI18N
        jButton1.setText("Reserve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/24x24/delete.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/24x24/new.png"))); // NOI18N
        jButton3.setText("New");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/WhatsApp Image 2017-10-21 at 8.37.13 AM.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(txtReqId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cmdhospital, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2))
                    .addComponent(txtReqId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdhospital, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdhospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhospitalActionPerformed
        System.out.println(" page came  >>>>>");
        SearchPopUp MAS = new SearchPopUp(null, true, 3, "0") {
            @Override
            public void getSelectedValue(String Para1, String para2, String para3, String para4, String para5) {
                try {
                    txtReqId.setText(Para1);

                    ResultSet set = null;
                    set = hdata.SearchHospital(para4);
                    set.beforeFirst();
                    set.next();
                    txtHospital.setText(set.getString("HName"));

                    txtConsulltent.setText(para5);

                    ResultSet rs = null;
                    BType = para2;
                    txtIDblood.setText(para2);
                    rs = btype.SearchBloodType(para2);
                    rs.beforeFirst();
                    rs.next();
                    txtRh.setText(rs.getString("RH"));
                    txtABO.setText(rs.getString("Type"));
                    // setval.setTypeid(para2);

                    txtVol.setText(para3);
                    showTableData();
                } catch (SQLException ex) {
                    Logger.getLogger(CompatabilityView.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        };
        MAS.setVisible(true);
        MAS = null;
    }//GEN-LAST:event_cmdhospitalActionPerformed

    private void txtReqIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReqIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReqIdActionPerformed

    private void txtConsulltentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsulltentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsulltentActionPerformed

    private void txtVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolActionPerformed

    private void txtHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalActionPerformed

    private void txtRhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRhActionPerformed

    private void txtABOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtABOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtABOActionPerformed

    private void cmdhospital1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhospital1ActionPerformed
        System.out.println(" page came  >>>>>");
        SearchPopUp MAS = new SearchPopUp(null, true, 4, txtIDblood.getText()) {
            @Override
            public void getSelectedValue(String Para1, String para2, String para3, String para4, String para5) {
                if (BType.trim().equals(para3.trim())) {
                    txtStockID1.setText(Para1);
                    txtVol1.setText(para2);
                } else {
                    JOptionPane.showMessageDialog(null, "Blood Type is not match");
                }
            }
        };
        MAS.setVisible(true);
        MAS = null;
    }//GEN-LAST:event_cmdhospital1ActionPerformed

    private void txtVol4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVol4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVol4ActionPerformed

    private void cmdhospital2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhospital2ActionPerformed
        System.out.println(" page came  >>>>>");
        SearchPopUp MAS = new SearchPopUp(null, true, 4, txtIDblood.getText()) {
            @Override
            public void getSelectedValue(String Para1, String para2, String para3, String para4, String para5) {
                if (BType.trim().equals(para3.trim())) {
                    txtStockID2.setText(Para1);
                    txtVol2.setText(para2);
                } else {
                    JOptionPane.showMessageDialog(null, "Blood Type is not match");
                }
            }
        };
        MAS.setVisible(true);
        MAS = null;
    }//GEN-LAST:event_cmdhospital2ActionPerformed

    private void txtStockID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockID2ActionPerformed

    private void cmdhospital3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhospital3ActionPerformed
        System.out.println(" page came  >>>>>");
        SearchPopUp MAS = new SearchPopUp(null, true, 4, txtIDblood.getText()) {
            @Override
            public void getSelectedValue(String Para1, String para2, String para3, String para4, String para5) {
                if (BType.trim().equals(para3.trim())) {
                    txtStockID3.setText(Para1);
                    txtVol3.setText(para2);
                } else {
                    JOptionPane.showMessageDialog(null, "Blood Type is not match");
                }
            }
        };
        MAS.setVisible(true);
        MAS = null;
    }//GEN-LAST:event_cmdhospital3ActionPerformed

    private void txtStockID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockID3ActionPerformed

    private void txtStockID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockID4ActionPerformed

    private void cmdhospital4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhospital4ActionPerformed
        System.out.println(" page came  >>>>>");
        SearchPopUp MAS = new SearchPopUp(null, true, 4, txtIDblood.getText()) {
            @Override
            public void getSelectedValue(String Para1, String para2, String para3, String para4, String para5) {
                if (BType.trim().equals(para3.trim())) {
                    txtStockID4.setText(Para1);
                    txtVol4.setText(para2);
                } else {
                    JOptionPane.showMessageDialog(null, "Blood Type is not match");
                }
            }
        };
        MAS.setVisible(true);
        MAS = null;
    }//GEN-LAST:event_cmdhospital4ActionPerformed

    private void txtStockID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockID1ActionPerformed

    private void txtVol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVol1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVol1ActionPerformed

    private void txtVol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVol2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVol2ActionPerformed

    private void txtVol3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVol3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVol3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Reserve", "Are you sure to reserve this Bloods ?", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            int vol = Integer.parseInt(txtVol.getText());
            int stocl1 = Integer.parseInt(txtVol1.getText());
            int stocl2 = Integer.parseInt(txtVol2.getText());
            int stocl3 = Integer.parseInt(txtVol3.getText());
            int stocl4 = Integer.parseInt(txtVol4.getText());
            if (vol >= stocl1 + stocl2 + stocl3 + stocl4) {
                boolean val1 = false, val2 = false, val3 = false, val4 = false;
                if (txtStockID1.getText().trim() != "0") {
                    val1 = stockdata.updateStock(txtStockID1.getText().trim(), Integer.valueOf(txtVol1.getText().trim()));
                }
                if (txtStockID1.getText().trim() != "0") {
                    val2 = stockdata.updateStock(txtStockID2.getText().trim(), Integer.valueOf(txtVol2.getText().trim()));
                }
                if (txtStockID1.getText().trim() != "0") {
                    val3 = stockdata.updateStock(txtStockID3.getText().trim(), Integer.valueOf(txtVol3.getText().trim()));
                }
                if (txtStockID1.getText().trim() != "0") {
                    val4 = stockdata.updateStock(txtStockID4.getText().trim(), Integer.valueOf(txtVol4.getText().trim()));
                }

                if (val1 && val2 && val3 && val4) {

                    int mas = redata.addResMas(txtReqId.getText().trim(), BType, (Integer.valueOf(txtVol1.getText().trim())) + (Integer.valueOf(txtVol2.getText().trim())) + (Integer.valueOf(txtVol3.getText().trim())) + (Integer.valueOf(txtVol4.getText().trim())));
                    if (mas > 0) {
                        redata.addResDetail(mas, txtStockID1.getText().trim(), txtStockID2.getText().trim(), txtStockID3.getText().trim(), txtStockID4.getText().trim());
                        boolean res = bloodrequestdata.updateRequest(txtReqId.getText().trim());
                        if (res) {
                            JOptionPane.showMessageDialog(null, "Reserved succuss.");
                        }
                        //   txtStockID1.setText("0");
                        //   txtVol1.setText("0");
                        NewForm();
                    } else {
                        JOptionPane.showMessageDialog(null, "Reserved faild.");
                    }
                }
            }else {
            JOptionPane.showMessageDialog(null,"Can't Reserve. vol Not match");}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        NewForm();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtIDbloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDbloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDbloodActionPerformed

    private void NewForm() {
        BType = "";
        txtReqId.setText("");
        txtHospitalName.setText("");
        txtVol.setText("");
        txtHospital.setText("");
        txtConsulltent.setText("");
        txtABO.setText("");
        txtRh.setText("");
        txtStockID1.setText("0");
        txtStockID2.setText("0");
        txtStockID3.setText("0");
        txtStockID4.setText("0");
        txtVol1.setText("0");
        txtVol2.setText("0");
        txtVol3.setText("0");
        txtVol4.setText("0");
        showTableData();
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblStock;
    private javax.swing.JButton cmdhospital;
    private javax.swing.JButton cmdhospital1;
    private javax.swing.JButton cmdhospital2;
    private javax.swing.JButton cmdhospital3;
    private javax.swing.JButton cmdhospital4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField txtABO;
    private javax.swing.JTextField txtConsulltent;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtIDblood;
    private javax.swing.JTextField txtReqId;
    private javax.swing.JTextField txtRh;
    private javax.swing.JTextField txtStockID1;
    private javax.swing.JTextField txtStockID2;
    private javax.swing.JTextField txtStockID3;
    private javax.swing.JTextField txtStockID4;
    private javax.swing.JTextField txtVol;
    private javax.swing.JTextField txtVol1;
    private javax.swing.JTextField txtVol2;
    private javax.swing.JTextField txtVol3;
    private javax.swing.JTextField txtVol4;
    // End of variables declaration//GEN-END:variables
}
