/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import MasterData.Class.BloodRequestData;
import MasterData.Class.BloodTypeData;
import MasterData.Class.ReservedData;
import Pannals.RequestView;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author chamod
 */
public class IshueBlood extends javax.swing.JInternalFrame {

    ReservedData reserved = new ReservedData();
    BloodTypeData btype = new BloodTypeData();
    BloodRequestData request = new BloodRequestData();

    /**
     * Creates new form IshueBlood
     */
    public IshueBlood() {
        initComponents();
        ShowGrid();
       showTableData();
    }

    private void ShowGrid() {
        String data[][] = null;
        String colu[] = new String[]{"Respond Id", "Request Id", "Blood Type", "Rh", "Reserved Vol"};
        DefaultTableModel model = new DefaultTableModel(data, colu) {
            //@Override
            public boolean isCellEditable(int x, int y) {
                return false;
            }
        };

        tblShowReserved.setModel(model);
        tblShowReserved.getTableHeader().setPreferredSize(new Dimension(tblShowReserved.getTableHeader().getPreferredSize().width, 35));
        JTableHeader head = tblShowReserved.getTableHeader();
        head.setFont(head.getFont().deriveFont(Font.BOLD));

        /* DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        RequestViewTable.getColumnModel().getColumn(4).setCellRenderer(rightRenderer); */
        TableColumn colou10 = tblShowReserved.getColumnModel().getColumn(0);
        colou10.setMinWidth(0);
        colou10.setPreferredWidth(0);
        colou10.setMaxWidth(0);

        /*TableColumn colou11 = RequestViewTable.getColumnModel().getColumn(1);
        colou11.setMinWidth(80);
        colou11.setPreferredWidth(80);
        colou11.setMaxWidth(80);

        TableColumnModel cm = RequestViewTable.getColumnModel();
        JComboBox type = new JComboBox();
        type.addItem("C");
        type.addItem("D");
        cm.getColumn(1).setCellEditor(new DefaultCellEditor(type));

        TableColumn colou12 = RequestViewTable.getColumnModel().getColumn(2);
        colou12.setMinWidth(120);
        colou12.setPreferredWidth(120);

        TableColumn colou13 = RequestViewTable.getColumnModel().getColumn(3);
        colou13.setMinWidth(90);
        colou13.setPreferredWidth(90);
        colou13.setPreferredWidth(110);

        TableColumn colou14 = RequestViewTable.getColumnModel().getColumn(4);
        colou14.setMinWidth(100);
        colou14.setPreferredWidth(100);
        colou14.setPreferredWidth(120);*/
    }

 
    public void showTableData() {
        ResultSet rs;
        DefaultTableModel dtf = new DefaultTableModel();
        dtf.setRowCount(0);
        try {
            rs = reserved.ShowReserved(txtRequestId.getText().trim());
            rs.last();

            int count = rs.getRow();
            rs.beforeFirst();
            String data[][] = null;
            data = new String[count][5];
            int x = 0;
            while (rs.next()) {
                Vector v = new Vector();
                dtf = (javax.swing.table.DefaultTableModel) tblShowReserved.getModel();
                v.add(data[x][0] = rs.getString("ResMas"));
                ResultSet rs1 =  btype.SearchBloodType(rs.getString("BType"));
                rs1.beforeFirst();
                rs1.next();
                v.add(data[x][1] = rs.getString("RequestId"));
                v.add(data[x][2] = rs1.getString("Type"));
                v.add(data[x][3] = rs1.getString("RH"));
                v.add(data[x][4] = rs.getString("ResVol"));
                dtf.addRow(v);
                // confirm = rs.getInt("confirm");
                x = x + 1;
            }
        } catch (SQLException ex) {
            Logger.getLogger(RequestView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRequestId = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowReserved = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BB : Blood Issue");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/be86d361-1ddd-43e3-8574-e04adf9904b7.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Reserved Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Request Id");

        txtRequestId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRequestIdActionPerformed(evt);
            }
        });
        txtRequestId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRequestIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRequestIdKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtRequestId, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRequestId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Issue Reserved Blood", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        tblShowReserved.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblShowReserved.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblShowReservedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblShowReserved);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/24x24/delete.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/WhatsApp Image 2017-10-21 at 8.37.13 AM.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel9))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblShowReservedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblShowReservedMouseClicked
        if (evt.getClickCount() == 2) {
            int a = JOptionPane.showConfirmDialog(null, "Are you sure to Issue blood ?", "Ishue", JOptionPane.YES_NO_OPTION);
            if (a == 0) {
                boolean val = reserved.updateIshu(tblShowReserved.getValueAt(tblShowReserved.getSelectedRow(), 1).toString());
                if (val) {
                    JOptionPane.showMessageDialog(null, "Issue is sucsess "); 
                    showTableData();
                } else {
                    JOptionPane.showMessageDialog(null, "Issue faild.");
                }
            }
        }
    }//GEN-LAST:event_tblShowReservedMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtRequestIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRequestIdKeyReleased
    showTableDataReqId();
    }//GEN-LAST:event_txtRequestIdKeyReleased

    private void txtRequestIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRequestIdActionPerformed
        
    }//GEN-LAST:event_txtRequestIdActionPerformed

    private void txtRequestIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRequestIdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRequestIdKeyTyped

    public void showTableDataReqId() {
        ResultSet rs;
        DefaultTableModel dtf = new DefaultTableModel();
       // DefaultTableModel dt = (DefaultTableModel) RequestViewTable.getModel();
        dtf.setRowCount(0);
        try {
            rs = request.ShowRequest(txtRequestId.getText().trim());
            rs.last();

            int count = rs.getRow();
            rs.beforeFirst();
            String data[][] = null;
            data = new String[count][5];
            int x = 0;
            while (rs.next()) {
                Vector v = new Vector();
                v.add(data[x][0] = rs.getString("HId"));
                
                ResultSet rs1 = btype.SearchBloodType(rs.getString("TypeId"));
                rs1.beforeFirst();
                rs1.next();
                v.add(data[x][1] = rs1.getString("Type")+rs1.getString("RH"));
               
                
                v.add(data[x][2] = rs.getString("Description"));
                v.add(data[x][3] = rs.getString("RequestVol"));
                v.add(data[x][4] = rs.getString("ConsultentName"));
                dtf.addRow(v);
                // confirm = rs.getInt("confirm");
                x = x + 1;
            }
        } catch (SQLException ex) {
            Logger.getLogger(RequestView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblShowReserved;
    private javax.swing.JTextField txtRequestId;
    // End of variables declaration//GEN-END:variables
}
